[package]
name = "dana"
version = "0.1.0"
edition = "2021"


[dependencies]
num-traits = "0.2.19"
typenum = "1.17.0"

[dependencies.dana_macros]
path = "dana_macros"

[dependencies.serde]
version = "1.0.203"
features = ["derive"]
optional = true


[dev-dependencies]
rand = "0.8.5"
trybuild = "1.0.96"

[dev-dependencies.criterion]
version = "0.5.1"
features = ["csv_output", "html_reports"]


[lib]
bench = false

[[bench]]
name = "qty_basic"
harness = false

[[bench]]
name = "qty_capacitor"
harness = false

[[bench]]
name = "qty_simd"
harness = false
required-features = ["simd"]


[features]
default = []
serde = ["dep:serde"]
simd = []
