[package]
name = "dana"
description = "Compile-time dimensional analysis via generic types."
version = "0.2.0"

readme = "README.md"

exclude = ["/.idea", "/.vscode", "*.sh", "*.tar.gz", "*.zip"]
categories = ["development-tools", "mathematics", "science"]
keywords = ["dimensional-analysis", "quantities", "units", "library"]

edition = "2021"


[dependencies]
num-traits = "0.2.19"
typenum = "1.17.0"

[dependencies.dana_macros]
path = "dana_macros"

[dependencies.chrono]
version = "0.4.38"
optional = true

[dependencies.rand]
version = "0.8.5"
optional = true

[dependencies.serde]
version = "1.0.203"
features = ["derive"]
optional = true


[dev-dependencies]
trybuild = "1.0.96"

[dev-dependencies.criterion]
version = "0.5.1"
features = ["csv_output", "html_reports"]


[lib]
bench = false

[[bench]]
name = "qty_basic"
harness = false

[[bench]]
name = "qty_capacitor"
harness = false

[[bench]]
name = "qty_simd"
harness = false
required-features = ["rand", "simd"]


[features]
default = []

chrono = ["dep:chrono"]
rand = ["dep:rand"]
serde = ["dep:serde"]
simd = []
