[package]
name = "dimensional"
version = "0.1.0"
edition = "2021"


[dependencies]
num-prime = "0.4.4"
num-traits = "0.2.19"

[dependencies.conv_macros]
path = "conv_macros"

[dependencies.serde]
version = "1.0.203"
features = ["derive"]
optional = true


[features]
default = []
#serde = ["dep:serde"]
