[package]
name = "dim_macros"
version = "0.1.0"
edition = "2021"
publish = false


[lib]
proc-macro = true


[dependencies]
quote = "1.0.36"
syn = "2.0.66"

[dependencies.proc-macro2]
version = "1.0.85"
features = ["span-locations"]
