name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Default build:
    - name: Build
      run: cargo build

#    # Featured build:
#    - name: Build with stable features
#      run: cargo build --features "chrono rand serde"

#    # Full build:
#    - name: Build with all features
#      run: cargo +nightly build --all-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

#    # Default tests:
#    - name: Build tests
#      run: cargo test --no-run
#    - name: Run tests
#      run: cargo test

    # Featured tests:
    - name: Build tests with stable features
      run: cargo test --features "chrono rand serde" --no-run
    - name: Run tests with stable features
      run: cargo test --features "chrono rand serde"

#    # Full tests:
#    - name: Build tests with all features
#      run: cargo +nightly test --all-features --no-run
#    - name: Run tests with all features
#      run: cargo +nightly test --all-features

  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Default benchmarks:
    - name: Build benchmarks
      run: cargo bench --no-run
    - name: Run benchmarks
      run: cargo bench

#    # Featured benchmarks:
#    - name: Build benchmarks with stable features
#      run: cargo bench --features "chrono rand serde" --no-run
#    - name: Run benchmarks
#      run: cargo bench --features "chrono rand serde"

#    # Full benchmarks:
#    - name: Build benchmarks with all features
#      run: cargo +nightly bench --all-features --no-run
#    - name: Run benchmarks
#      run: cargo +nightly bench --all-features
